// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestBackend.Models;

public partial class Store
{
    public int Id { get; set; }

    public int ProductsId { get; set; }

    public string Storename { get; set; }

    public int Qty { get; set; }
}